### ISSUE TITLE
Cannot collapse children

### ISSUE THREAD

**Issue by bcourtney5965** [dabeng/OrgChart.js#17]
I would like to collapse children nodes, but its's not working, I'm not even getting the little chevrons to popup on-hover & allow you to collapse/hide the children nodes. 

 I think I'm having two problems:
1.) Getting the Chevron's to appear and the functionality associated with them
2.) perhaps some logic that I've failed to implement or implemented in correctly

Here's the output:
![screen shot 2017-10-27 at 11 50 57 am](https://user-images.githubusercontent.com/7043747/32120435-60acb342-bb0d-11e7-9da6-cdbfae946e50.png)

And here's the output when I hover on the root node (notice no chevrons):
![screen shot 2017-10-27 at 11 53 04 am](https://user-images.githubusercontent.com/7043747/32120468-893de006-bb0d-11e7-8283-0e7d788271b0.png)

I'm using React but it's pretty simple - here's my code:
```
var myData = {
  'name': 'Lao Lao',
  'title': 'general manager',
  'children': [
    { 'name': 'Bo Miao', 'title': 'department manager' },
    {
      'name': 'Su Miao', 'title': 'department manager',
      'children': [
        { 'name': 'Tie Hua', 'title': 'senior engineer' },
        {
          'name': 'Hei Hei', 'title': 'senior engineer',
          'children': [
            { 'name': 'Pang Pang', 'title': 'engineer' },
            { 'name': 'Xiang Xiang', 'title': 'UE engineer' }
          ]
        }
      ]
    },
    { 'name': 'Yu Jie', 'title': 'department manager' },
    { 'name': 'Yu Li', 'title': 'department manager' },
    { 'name': 'Hong Miao', 'title': 'department manager' },
    { 'name': 'Yu Wei', 'title': 'department manager' },
    { 'name': 'Chun Miao', 'title': 'department manager' },
    { 'name': 'Yu Tie', 'title': 'department manager' }
  ]
}
export class HierarchyComponent extends React.Component {
  componentDidMount() {
    new OrgChart({
      'chartContainer': '#chart-container',
      'data': myData,
      'nodeContent': 'title'
    });
  }

  render() {
    return (
      <div id="chart-container"  style={{ width: "91%" }}>
      </div>
    );
  }
}


```

**Comment by bcourtney5965** [comment]
Nevermind, I needed to add in font awesome.  Now everything works

**Comment by srameshr** [comment]
How are you getting the ```OrgChart``` variable? ```import OrgChart from 'orgchart'```
